# Metadados da aplica칞칚o para o cat치logo DGB
name: "An치lise de Not칤cias GovBR"
description: "Dashboard interativo para an치lise temporal de not칤cias do portal gov.br por ag칡ncia governamental"
owner:
  name: "Nitai Bezerra"
  email: "nitai@example.com"
category: "analytics"
tags:
  - "governo"
  - "not칤cias"
  - "an치lise-temporal"
  - "huggingface"
  - "govbr"
keywords: "noticias, governo, govbr, analise, dashboard, temporal, agencias"
icon: "游닗"
version: "1.0.0"
repository: "https://github.com/destaquesgovbr/streamlit-dgb-basic"
documentation: "https://github.com/destaquesgovbr/streamlit-dgb-basic/blob/main/README.md"
